# Generated by Django 3.1.5 on 2021-02-04 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210131_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentbalancewithdraw',
            name='transection_id',
            field=models.TextField(blank=True, default='Pending', null=True),
        ),
    ]
