# Generated by Django 3.1.5 on 2021-02-06 05:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0003_agentbalancewithdraw_transection_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agnetbalance',
            name='agent',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agnetbalance', to=settings.AUTH_USER_MODEL),
        ),
    ]
