# Generated by Django 3.1.5 on 2021-02-08 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0004_auto_20210206_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentbalancewithdraw',
            name='transection_id',
            field=models.TextField(blank=True, default='0', null=True),
        ),
        migrations.CreateModel(
            name='AdminAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btc_address', models.CharField(blank=True, max_length=250, null=True)),
                ('amount', models.FloatField(default=0.0)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='adminaccount', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
