# Generated by Django 3.1.5 on 2021-02-02 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marketing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_text', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
