# Generated by Django 3.1.5 on 2021-02-02 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_marketing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_question', models.TextField(blank=True, null=True)),
                ('question_details', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
