# Generated by Django 3.1.5 on 2021-02-02 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='add_question',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
