# Generated by Django 3.1.5 on 2021-02-03 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='full_name',
            new_name='name',
        ),
    ]
