# Generated by Django 3.1.5 on 2021-02-03 13:47

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_auto_20210203_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='about_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
