# Generated by Django 3.1.5 on 2021-02-08 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0011_termscondition'),
    ]

    operations = [
        migrations.CreateModel(
            name='navbarSupportedContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('body', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('body', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
