# Generated by Django 3.1.5 on 2021-02-08 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0012_navbarsupportedcontent_usercontent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserContent',
            new_name='UserDashboardContent',
        ),
    ]
