# Generated by Django 3.1.5 on 2021-02-08 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0013_auto_20210208_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdashboardcontent',
            name='body',
        ),
    ]
