# Generated by Django 3.1.5 on 2021-01-30 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_type', models.CharField(choices=[('ALL_MEMBER', 'all_member'), ('AGENT', 'agent'), ('MEMBERS', 'members'), ('WINNER', 'winner')], default='all_member', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('duration', models.DateField(null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('body', models.TextField(blank=True, max_length=300, null=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Notification',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PackageBalance',
            fields=[
                ('package', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='package', serialize=False, to='user_profile.package')),
                ('profit_percentage', models.FloatField(default=2.5)),
                ('sponsor_percentage', models.FloatField(default=15.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
