# Generated by Django 3.1.5 on 2021-02-06 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='agent_balance',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='current_wallet',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='sponsor_wallet',
        ),
    ]
