# Generated by Django 3.1.5 on 2021-02-14 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_auto_20210206_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='BTCAddress',
        ),
    ]
